### ISSUE TITLE
Problem with forge-gltf-server

### ISSUE THREAD

**Issue by DominikJanecky** [petrbroz/forge-gltf-server#6]
Hello, when trying your server method I always get the same error (Figures 1,2,3). 

![issue1](https://user-images.githubusercontent.com/22544042/114157537-05cb1600-9924-11eb-962d-213596edc32e.png)
![issue2](https://user-images.githubusercontent.com/22544042/114157384-dfa57600-9923-11eb-98a3-ddc9c59353e9.png)
![issue3](https://user-images.githubusercontent.com/22544042/114157390-e0d6a300-9923-11eb-8691-7cfe9bb07ec4.png)

I have the same problem even if I run your server method on my PC, connect to localhost and want to click on login.
Can you advise me where I can make a mistake? I've already tried everything and the same error gives me your link "forge-gltf-server.herokuapp.com" too...I'm not sure if the error is on my side and if I'm able to fix it.

Thank you very much for your help in resolving this issue and for your time.

**Comment by petrbroz** [comment]
Thank you for the heads up @DominikJanecky. The problem has to do with the "callback URL" that you typically specify when creating a new Forge app, and that must match exactly the callback URL your application code uses. Unfortunately, I've got too many samples running on Heroku, and sometimes I use the same Forge credentials for multiple demos which is causing problems - whenever I change the callback URL for one of the demos, other demos stop working... I've updated the callback for the Forge app and the app should be back online now.

**Comment by petrbroz** [comment]
When you run the server yourself, just make sure that the callback URL for your Forge app uses the following format: `${HOST_URL}/auth/callback` (for example, `http://localhost:3000/auth/callback`), because that's the URL the server code will use: https://github.com/petrbroz/forge-gltf-server/blob/develop/config.js#L19.

**Comment by DominikJanecky** [comment]
Yeah, thanks. That really helped me a lot. I had a mistake in callback URL in my forge app :)
