### ISSUE TITLE
oAuth login problem

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-gltf-server#9]
Redirection failed...
![Screen Shot 2022-01-31 at 8 57 14 PM](https://user-images.githubusercontent.com/440241/151914940-735d12ef-a823-4c55-8309-92714ef543cd.JPG)

**Comment by petrbroz** [comment]
Sorry... as usual, I was sharing one set of Forge credentials among multiple demos, and had to change the redirect URI for the "other" demo. Now https://forge-gltf-server.herokuapp.com is using its own client ID and secret, so we should be good.
